<Project>
  <PropertyGroup>
    <Company>The Melding Wars</Company>
    <Product>Aero</Product>
    <Copyright>Copyright © 2021-2026 The Melding Wars</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <RepositoryUrl>https://github.com/themeldingwars/Aero</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
