// <auto-generated>
//   Generated by Aero.ProtocolGen from Sift protocol dumps. DO NOT EDIT.
//   Regenerate with: dotnet run --project Aero.ProtocolGen -- --dumps <dumpsDir> --out <outDir>
//   Dump content hash: 8AF72793FBDA3729E1FD05FEFBF454E8BCA3BD2222779E37E6A7C2A96F5BA090
// </auto-generated>
using System.Collections.Generic;

namespace Aero.Protocol
{
    /// Universal Matrix protocol message ids. Values are stable: new messages are appended, existing members never move.
    public enum MatrixMessage
    {
        Announce,
        ChallengeStateUpdate,
        ClientPreferences,
        ClientStatus,
        DEV_ExecuteCommand,
        EnterZone,
        EnterZoneAck,
        ExitZone,
        ExitZoneAck,
        GamePaused,
        KeyframeRequest,
        Login,
        MatchQueueResponse,
        MatrixStatus,
        Referee_ExecuteCommand,
        RequestGhosts,
        ScopeInHint,
        SetPriorityBoost,
        SuperPing,
        SuperPong,
        SynchronizationRequest,
        SynchronizationResponse,
        TransferInstance,
        UpdateZoneTimeSync,
        WelcomeToTheMatrix,
        ForceUnqueue,
        FoundMatchUpdate,
        MatchQueueUpdate,
        ChallengeInvitation,
        ChallengeInvitationCancel,
        ChallengeInvitationResponse,
        ChallengeInvitationSquadInfoAck,
        ChallengeJoinResponse,
        ChallengeKicked,
        ChallengeLeave,
        ChallengeMatchParametersUpdate,
        ChallengeMatchStarting,
        ChallengeReadyCheck,
        ChallengeRosterUpdate,
        RequestPause,
        RequestResume,
        ServerProfiler_RequestNames,
        ServerProfiler_SendFrame,
        ServerProfiler_SendNames,
        StressTestMasterObject,
        ZoneQueueUpdate,
        DebugLagSample,
        DebugLagSampleClient,
        DebugLagSampleSim,
        LFGLeaderChange,
        LFGMatchFound,
        HotfixLevelChanged,
        LogInstrumentation,
        RequestSigscan,
        SigscanData,
        ReceiveEmergencyChat,
        SendEmergencyChat,
        UpdateDevZoneInfo
    }

    /// Maps universal Matrix message enums to per-version wire ids.
    public static class MatrixTables
    {
        public const int VersionCount = 26;
        public const int MessageCount = 58;

        // [versionIndex, messageOrdinal] -> wire id, 0 = the message does not exist in that version
        private static readonly byte[,] MessageIds =
        {
            { 14, 22, 9, 8, 6, 15, 2, 17, 3, 24, 4, 1, 21, 19, 7, 5, 18, 10, 12, 25, 23, 11, 20, 16, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 14, 22, 9, 8, 6, 15, 2, 17, 3, 24, 4, 1, 21, 19, 7, 5, 18, 10, 12, 25, 23, 11, 20, 16, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 14, 24, 9, 8, 6, 15, 2, 17, 3, 27, 4, 1, 21, 19, 7, 5, 18, 10, 12, 28, 26, 11, 20, 16, 13, 25, 23, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 14, 24, 9, 8, 6, 15, 2, 17, 3, 27, 4, 1, 21, 19, 7, 5, 18, 10, 12, 28, 26, 11, 20, 16, 13, 25, 23, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 18, 0, 11, 10, 6, 19, 2, 21, 3, 40, 4, 1, 24, 23, 7, 5, 22, 12, 14, 41, 39, 13, 0, 20, 17, 38, 26, 25, 28, 30, 31, 29, 27, 32, 33, 36, 37, 35, 34, 8, 9, 16, 43, 42, 15, 44, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 18, 0, 11, 10, 6, 19, 2, 21, 3, 40, 4, 1, 24, 23, 7, 5, 22, 12, 14, 41, 39, 13, 0, 20, 17, 38, 26, 25, 28, 30, 31, 29, 27, 32, 33, 36, 37, 35, 34, 8, 9, 16, 43, 42, 15, 44, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 18, 0, 11, 10, 6, 19, 2, 21, 3, 40, 4, 1, 24, 23, 7, 5, 22, 12, 14, 41, 39, 13, 0, 20, 17, 38, 26, 25, 28, 30, 31, 29, 27, 32, 33, 36, 37, 35, 34, 8, 9, 16, 43, 42, 15, 44, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 16, 0, 10, 9, 5, 17, 2, 19, 3, 38, 4, 1, 22, 21, 6, 0, 20, 0, 12, 39, 37, 11, 0, 18, 15, 36, 24, 23, 26, 28, 29, 27, 25, 30, 31, 34, 35, 33, 32, 7, 8, 14, 41, 40, 13, 42, 0, 44, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 16, 0, 10, 9, 5, 17, 2, 19, 3, 38, 4, 1, 22, 21, 6, 0, 20, 0, 12, 39, 37, 11, 0, 18, 15, 36, 24, 23, 26, 28, 29, 27, 25, 30, 31, 34, 35, 33, 32, 7, 8, 14, 41, 40, 13, 42, 0, 44, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 16, 0, 10, 9, 5, 17, 2, 19, 3, 38, 4, 1, 22, 21, 6, 0, 20, 0, 12, 39, 37, 11, 0, 18, 15, 36, 24, 23, 26, 28, 29, 27, 25, 30, 31, 34, 35, 33, 32, 7, 8, 14, 41, 40, 13, 42, 0, 44, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 16, 0, 10, 9, 5, 17, 2, 19, 3, 37, 4, 1, 21, 20, 6, 0, 0, 0, 12, 38, 36, 11, 0, 18, 15, 35, 23, 22, 25, 27, 28, 26, 24, 29, 30, 33, 34, 32, 31, 7, 8, 14, 40, 39, 13, 41, 0, 43, 42, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 32, 0, 26, 25, 21, 33, 18, 35, 19, 53, 20, 17, 37, 36, 22, 0, 0, 0, 28, 54, 52, 27, 0, 34, 31, 51, 39, 38, 41, 43, 44, 42, 40, 45, 46, 49, 50, 48, 47, 23, 24, 30, 56, 55, 29, 57, 0, 59, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 32, 0, 26, 25, 21, 33, 18, 35, 19, 53, 20, 17, 37, 36, 22, 0, 0, 0, 28, 54, 52, 27, 0, 34, 31, 51, 39, 38, 41, 43, 44, 42, 40, 45, 46, 49, 50, 48, 47, 23, 24, 30, 56, 55, 29, 57, 0, 59, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
            { 32, 0, 26, 25, 21, 33, 18, 35, 19, 53, 20, 17, 37, 36, 22, 0, 0, 0, 28, 54, 52, 27, 0, 34, 31, 51, 39, 38, 41, 43, 44, 42, 40, 45, 46, 49, 50, 48, 47, 23, 24, 30, 56, 55, 29, 57, 0, 59, 58, 61, 60, 0, 0, 0, 0, 0, 0, 0 },
            { 32, 0, 26, 25, 21, 33, 18, 36, 19, 54, 20, 17, 38, 37, 22, 0, 0, 0, 28, 55, 53, 27, 0, 34, 31, 52, 40, 39, 42, 44, 45, 43, 41, 46, 47, 50, 51, 49, 48, 23, 24, 30, 57, 56, 29, 58, 0, 60, 59, 62, 61, 35, 0, 0, 0, 0, 0, 0 },
            { 32, 0, 26, 25, 21, 33, 18, 36, 19, 54, 20, 17, 38, 37, 22, 0, 0, 0, 28, 55, 53, 27, 0, 34, 31, 52, 40, 39, 42, 44, 45, 43, 41, 46, 47, 50, 51, 49, 48, 23, 24, 30, 57, 56, 29, 58, 0, 60, 59, 62, 61, 35, 0, 0, 0, 0, 0, 0 },
            { 32, 0, 26, 25, 21, 33, 18, 36, 19, 54, 20, 17, 38, 37, 22, 0, 0, 0, 28, 55, 53, 27, 0, 34, 31, 52, 40, 39, 42, 44, 45, 43, 41, 46, 47, 50, 51, 49, 48, 23, 24, 30, 57, 56, 29, 58, 0, 60, 59, 62, 61, 35, 0, 0, 0, 0, 0, 0 },
            { 35, 0, 26, 25, 21, 36, 18, 39, 19, 57, 20, 17, 41, 40, 22, 0, 0, 0, 28, 58, 56, 27, 0, 37, 34, 55, 43, 42, 45, 47, 48, 46, 44, 49, 50, 53, 54, 52, 51, 23, 24, 30, 60, 59, 29, 61, 0, 63, 62, 65, 64, 38, 31, 32, 33, 0, 0, 0 },
            { 35, 0, 26, 25, 21, 36, 18, 39, 19, 57, 20, 17, 41, 40, 22, 0, 0, 0, 28, 58, 56, 27, 0, 37, 34, 55, 43, 42, 45, 47, 48, 46, 44, 49, 50, 53, 54, 52, 51, 23, 24, 30, 60, 59, 29, 61, 0, 63, 62, 65, 64, 38, 31, 32, 33, 0, 0, 0 },
            { 35, 0, 26, 25, 21, 36, 18, 39, 19, 57, 20, 17, 41, 40, 22, 0, 0, 0, 28, 58, 56, 27, 0, 37, 34, 55, 43, 42, 45, 47, 48, 46, 44, 49, 50, 53, 54, 52, 51, 23, 24, 30, 60, 59, 29, 61, 0, 63, 62, 65, 64, 38, 31, 32, 33, 0, 0, 0 },
            { 35, 0, 26, 25, 21, 36, 18, 39, 19, 57, 20, 17, 41, 40, 22, 0, 0, 0, 28, 58, 56, 27, 0, 37, 34, 55, 43, 42, 45, 47, 48, 46, 44, 49, 50, 53, 54, 52, 51, 23, 24, 30, 60, 59, 29, 61, 0, 63, 62, 65, 64, 38, 31, 32, 33, 0, 0, 0 },
            { 35, 0, 26, 25, 21, 36, 18, 39, 19, 57, 20, 17, 41, 40, 22, 0, 0, 0, 28, 58, 56, 27, 0, 37, 34, 55, 43, 42, 45, 47, 48, 46, 44, 49, 50, 53, 54, 52, 51, 23, 24, 30, 60, 59, 29, 61, 0, 63, 62, 65, 64, 38, 31, 32, 33, 0, 0, 0 },
            { 35, 0, 26, 25, 21, 36, 18, 39, 19, 57, 20, 17, 41, 40, 22, 0, 0, 0, 28, 58, 56, 27, 0, 37, 34, 55, 43, 42, 45, 47, 48, 46, 44, 49, 50, 53, 54, 52, 51, 23, 24, 30, 60, 59, 29, 61, 0, 63, 62, 65, 64, 38, 31, 32, 33, 0, 0, 0 },
            { 35, 0, 26, 25, 21, 36, 18, 39, 19, 57, 20, 17, 41, 40, 22, 0, 0, 0, 28, 58, 56, 27, 0, 37, 34, 55, 43, 42, 45, 47, 48, 46, 44, 49, 50, 53, 54, 52, 51, 23, 24, 30, 60, 59, 29, 61, 0, 63, 62, 65, 64, 38, 31, 32, 33, 0, 0, 0 },
            { 36, 0, 26, 25, 21, 37, 18, 40, 19, 58, 20, 17, 42, 41, 22, 0, 0, 0, 28, 59, 57, 27, 0, 38, 35, 56, 44, 43, 46, 48, 49, 47, 45, 50, 51, 54, 55, 53, 52, 23, 24, 30, 61, 60, 29, 62, 0, 64, 63, 66, 65, 39, 31, 32, 34, 67, 33, 0 },
            { 36, 0, 26, 25, 21, 37, 18, 40, 19, 58, 20, 17, 42, 41, 22, 0, 0, 0, 28, 59, 57, 27, 0, 38, 35, 56, 44, 43, 46, 48, 49, 47, 45, 50, 51, 54, 55, 53, 52, 23, 24, 30, 61, 60, 29, 62, 0, 64, 63, 66, 65, 39, 31, 32, 34, 67, 33, 68 },
        };

        private static readonly Dictionary<int, int> IdToOrdinal = new(VersionCount * MessageCount);
        static MatrixTables()
        {
            for (int v = 0; v < VersionCount; v++)
            {
                for (int m = 0; m < MessageCount; m++)
                {
                    byte id = MessageIds[v, m];
                    if (id != 0)
                        IdToOrdinal[(v << 8) | id] = m;
                }
            }
        }

        public static byte GetMessageId(MatrixVersion version, MatrixMessage message) => MessageIds[(int)version, (int)message];

        /// Returns the ordinal of the message with the given wire id in the given version, or -1 if the id is unknown for that version.
        public static int FindMessage(MatrixVersion version, byte messageId)
        {
            int key = ((int)version << 8) | messageId;
            return IdToOrdinal.TryGetValue(key, out int ordinal) ? ordinal : -1;
        }

        /// Gets the wire id for a Matrix message in a version. Returns false if the message is absent in that version.
        public static bool TryGetMessageId(MatrixVersion version, MatrixMessage message, out byte messageId)
        {
            messageId = GetMessageId(version, message);
            return messageId != 0;
        }
    }
}
