// <auto-generated>
//   Generated by Aero.ProtocolGen from Sift protocol dumps. DO NOT EDIT.
//   Regenerate with: dotnet run --project Aero.ProtocolGen -- --dumps <dumpsDir> --out <outDir>
//   Dump content hash: 6B48F2AA5E9DD86A96F2DFD339A1BAA883F227A34D925E1E1BBF984A36083962
// </auto-generated>

namespace Aero.Protocol
{
    /// Universal GSS Vehicle view ids. Values are stable: new members are appended, existing members never move.
    public enum GssVehicleView
    {
        BaseController,
        CombatController,
        CombatView,
        ObserverView,
        MovementView
    }

    /// Universal GSS Vehicle message ids. Values are stable: new members are appended, existing members never move.
    public enum GssVehicleMessage
    {
        AbilityActivated,
        AbilityFailed,
        PublicCombatLog,
        TookDebugHit,
        WeaponProjectileFired,
        CurrentPoseUpdate,
        TookDebugWeaponHitPublic,
        ForcedMovement,
        ForcedMovementCancelled,
        FlipPunch,
        DebugMovementUpdate
    }

    /// Universal GSS Vehicle command ids. Values are stable: new members are appended, existing members never move.
    public enum GssVehicleCommand
    {
        ActivateAbility,
        DeactivateAbility,
        FireBurst,
        FireEnd,
        FireWeaponProjectile,
        MovementInput,
        ReceiveCollisionDamage,
        SetWaterLevel,
        SinAcquire_Source,
        SetEffectsFlag,
        MovementInputFake,
        SetWaterLevelAndDesc
    }
}
