// <auto-generated>
//   Generated by Aero.ProtocolGen from Sift protocol dumps. DO NOT EDIT.
//   Regenerate with: dotnet run --project Aero.ProtocolGen -- --dumps <dumpsDir> --out <outDir>
//   Dump content hash: 6B48F2AA5E9DD86A96F2DFD339A1BAA883F227A34D925E1E1BBF984A36083962
// </auto-generated>

namespace Aero.Protocol
{
    /// Universal GSS Turret view ids. Values are stable: new members are appended, existing members never move.
    public enum GssTurretView
    {
        BaseController,
        ObserverView
    }

    /// Universal GSS Turret message ids. Values are stable: new members are appended, existing members never move.
    public enum GssTurretMessage
    {
        TookDebugHit,
        WeaponProjectileFired
    }

    /// Universal GSS Turret command ids. Values are stable: new members are appended, existing members never move.
    public enum GssTurretCommand
    {
        FireBurst,
        FireEnd,
        FireWeaponProjectile,
        PoseUpdate,
        ReportProjectileHit
    }
}
