// <auto-generated>
//   Generated by Aero.ProtocolGen from Sift protocol dumps. DO NOT EDIT.
//   Regenerate with: dotnet run --project Aero.ProtocolGen -- --dumps <dumpsDir> --out <outDir>
//   Dump content hash: 6B48F2AA5E9DD86A96F2DFD339A1BAA883F227A34D925E1E1BBF984A36083962
// </auto-generated>
using System;

namespace Aero.Gen.Attributes
{
    using Aero.Protocol;

    public partial class AeroMessageIdAttribute
    {
        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, MatrixMessage msg, MatrixVersion from = (MatrixVersion)0, MatrixVersion to = (MatrixVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(MatrixMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(MatrixVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssMessage msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssAnchorView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssAnchorView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssAreaVisualDataView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssAreaVisualDataView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssAreaVisualDataMessage msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssAreaVisualDataMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssAreaVisualDataMessage msg, GssAreaVisualDataView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssAreaVisualDataMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssAreaVisualDataView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssCharacterView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssCharacterView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssCharacterMessage msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssCharacterMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssCharacterCommand msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssCharacterCommand);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssCharacterMessage msg, GssCharacterView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssCharacterMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssCharacterView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssCharacterCommand msg, GssCharacterView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssCharacterCommand);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssCharacterView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssDeployableView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssDeployableView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssDeployableMessage msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssDeployableMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssDeployableMessage msg, GssDeployableView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssDeployableMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssDeployableView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssMeldingView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssMeldingView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssMeldingBubbleView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssMeldingBubbleView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssOutpostView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssOutpostView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssResourceNodeView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssResourceNodeView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssTurretView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssTurretView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssTurretMessage msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssTurretMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssTurretCommand msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssTurretCommand);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssTurretMessage msg, GssTurretView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssTurretMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssTurretView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssTurretCommand msg, GssTurretView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssTurretCommand);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssTurretView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssVehicleView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssVehicleView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssVehicleMessage msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssVehicleMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssVehicleCommand msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssVehicleCommand);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssVehicleMessage msg, GssVehicleView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssVehicleMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssVehicleView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssVehicleCommand msg, GssVehicleView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssVehicleCommand);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssVehicleView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssEncounterProxyView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssEncounterProxyView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssResourceAreaView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssResourceAreaView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssCarryableObjectView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssCarryableObjectView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssEncounterCommand msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssEncounterCommand);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssLootStoreExtensionView msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssLootStoreExtensionView);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssLootStoreExtensionMessage msg, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssLootStoreExtensionMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, GssLootStoreExtensionMessage msg, GssLootStoreExtensionView view, GssVersion from = (GssVersion)0, GssVersion to = (GssVersion)(-1))
            : this()
        {
            Typ = typ;
            Src = src;
            MessageEnum = nameof(GssLootStoreExtensionMessage);
            MessageOrdinal = (int)msg;
            MessageName = msg.ToString();
            ViewEnum = nameof(GssLootStoreExtensionView);
            ViewOrdinal = (int)view;
            ViewName = view.ToString();
            VersionEnum = nameof(GssVersion);
            VersionFrom = (int)from;
            VersionTo = (int)to;
        }

    }
}
