// <auto-generated>
//   Generated by Aero.ProtocolGen from Sift protocol dumps. DO NOT EDIT.
//   Regenerate with: dotnet run --project Aero.ProtocolGen -- --dumps <dumpsDir> --out <outDir>
//   Dump content hash: 8AF72793FBDA3729E1FD05FEFBF454E8BCA3BD2222779E37E6A7C2A96F5BA090
// </auto-generated>

namespace Aero.Protocol
{
    /// Universal GSS CarryableObject view ids. Values are stable: new members are appended, existing members never move.
    public enum GssCarryableObjectView
    {
        ObserverView
    }
}
