using System;
using System.Text;

namespace Aero.Gen.Attributes
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    public partial class AeroMessageIdAttribute : Attribute
    {
        public static string Name = "AeroMessageId";

        public MsgType Typ;
        public MsgSrc  Src;

        // Control messages: plain numeric id.
        public int MessageId;

        // Matrix/GSS messages: universal protocol enum reference + version range.
        public string MessageEnum;
        public int    MessageOrdinal;
        public string MessageName;
        public string VersionEnum;
        public int    VersionFrom; // version enum ordinal, 0 = V1
        public int    VersionTo;   // version enum ordinal, -1 = last known version (normalised by the generator)

        // GSS messages/commands only: the view/controller route the message is sent on.
        // null/ViewOrdinal < 0 = sent via the plain namespace route.
        public string ViewEnum;
        public int    ViewOrdinal;
        public string ViewName;

        public string FullClassName;

        private AeroMessageIdAttribute() { }

        public AeroMessageIdAttribute(MsgType typ, MsgSrc src, int messageId)
        {
            if (typ != MsgType.Control)
                throw new ArgumentException($"AeroMessageId with a numeric id can only be used for Control messages, got {typ}", nameof(typ));

            Typ       = typ;
            Src       = src;
            MessageId = messageId;
        }

        // The Matrix/GSS overloads (protocol enum + optional version range) are generated by
        // Aero.ProtocolGen from the Sift dumps, see Protocol/AeroMessageIdAttribute.Protocol.cs

        internal static AeroMessageIdAttribute CreateProtocol(MsgType typ, MsgSrc src, string messageEnum, int messageOrdinal, string messageName, string versionEnum, int versionFrom, int versionTo, string viewEnum = null, int viewOrdinal = -1, string viewName = null)
        {
            var attr = new AeroMessageIdAttribute();
            attr.Typ            = typ;
            attr.Src            = src;
            attr.MessageEnum    = messageEnum;
            attr.MessageOrdinal = messageOrdinal;
            attr.MessageName    = messageName;
            attr.VersionEnum    = versionEnum;
            attr.VersionFrom    = versionFrom;
            attr.VersionTo      = versionTo;
            attr.ViewEnum       = viewEnum;
            attr.ViewOrdinal    = viewOrdinal;
            attr.ViewName       = viewName;
            return attr;
        }

        public bool IsControl => MessageEnum == null;

        public string GetAsString()
        {
            if (IsControl)
                return $"{Typ}_{Src}_id{MessageId}";

            var sb = new StringBuilder($"{Typ}_{Src}_{MessageEnum}_{MessageName}");
            if (ViewOrdinal >= 0)
                sb.Append($"_{ViewEnum}_{ViewName}");
            sb.Append($"_V{VersionFrom + 1}_V{VersionTo + 1}");
            return sb.ToString();
        }

        public enum MsgType : byte
        {
            Control,
            Matrix,
            GSS
        }

        public enum MsgSrc : byte
        {
            Command,
            Message,
            Both
        }
    }
}
